import requests

def send_post_requests(base_url, routes, data):
    """
    Sends POST requests to multiple API routes with the provided data.

    :param base_url: The base URL of the server.
    :param routes: List of route paths to send POST requests to.
    :param data: Dictionary of data to include in the POST request.
    """
    for i,route in enumerate(routes):
        url = f"{base_url}/{route}"
        try:
            if i == 0:
                print("register")
                for i in data:
                    response = requests.post(url, json=i)
                    print(f"POST to {url} | Status Code: {response.status_code}")
            if i == 1:
                print("course add")
                data = [
                    {"course_code": "cs1",
                    "course_name": "Python",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 1},
                    {"course_code": "cs2",
                    "course_name": "C prog.",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 1},
                    {"course_code": "cs3",
                    "course_name": "Java",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 2},
                    {"course_code": "cs4",
                    "course_name": "C++",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 2},
                    {"course_code": "cs5",
                    "course_name": "Data Structures",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 3},
                    {"course_code": "cs6",
                    "course_name": "Algorithms",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 3},
                    {"course_code": "cs7",
                    "course_name": "Operating Systems",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 4},
                    {"course_code": "cs8",
                    "course_name": "Networks",
                    "department_id": 1,
                    "domain_id": 1,
                    "year": 4}
                ]
                department_codes = { 2: 'AI&DS', 3: 'ECE', 4: 'CSBS', 5: 'IT',
                    6: 'S&H', 7: 'MECH', 8: 'CYS', 9: 'AI&ML'
                }
                data.extend([
                    {"course_code": f"{department_codes[dept_id].lower()}{dept_id+year+j}",
                    "course_name": f"{department_codes[dept_id][:2]} {dept_id+year+j}",
                    "department_id": dept_id,
                    "domain_id": 1,
                    "year": year}
                    for dept_id in range(2, 10)
                    for year in range(1, 5)
                    for j in range(2)
                ])
                for i in data:
                    response = requests.post(url, json=i)
                    print(f"POST to {url} | Status Code: {response.status_code}")
            if i==2:
                data = [
                    {"course_code": "cs1",
                     "class_id": 111,
                     "uid": 101},
                    {"course_code": "cs1",
                     "class_id": 112,
                     "uid": 102},
                    {"course_code": "cs2",
                     "class_id": 111,
                     "uid": 101},
                    {"course_code": "cs2",
                     "class_id": 112,
                     "uid": 102},
                    {"course_code": "cs3",
                     "class_id": 121,
                     "uid": 101},
                    {"course_code": "cs3",
                     "class_id": 122,
                     "uid": 102},
                    {"course_code": "cs4",
                     "class_id": 121,
                     "uid": 101},
                    {"course_code": "cs4",
                     "class_id": 122,
                     "uid": 102},
                    {"course_code": "cs5",
                     "class_id": 131,
                     "uid": 101},
                    {"course_code": "cs5",
                     "class_id": 132,
                     "uid": 102},
                    {"course_code": "cs6",
                     "class_id": 131,
                     "uid": 101},
                    {"course_code": "cs6",
                     "class_id": 132,
                     "uid": 102},
                    {"course_code": "cs7",
                     "class_id": 141,
                     "uid": 101},
                    {"course_code": "cs7",
                     "class_id": 142,
                     "uid": 102},
                    {"course_code": "cs8",
                     "class_id": 141,
                     "uid": 101},
                    {"course_code": "cs8",
                     "class_id": 142,
                     "uid": 102},
                    {"course_code": "ai&ds3",
                     "class_id": 211,
                     "uid": 110},
                    {"course_code": "ai&ds3",
                     "class_id": 212,
                     "uid": 111},
                    {"course_code": "ai&ds4",
                     "class_id": 221,
                     "uid": 110},
                    {"course_code": "ai&ds4",
                     "class_id": 222,
                     "uid": 111},
                    {"course_code": "ai&ds5",
                     "class_id": 231,
                     "uid": 110},
                    {"course_code": "ai&ds5",
                     "class_id": 232,
                     "uid": 111},
                    {"course_code": "ai&ds6",
                     "class_id": 241,
                     "uid": 110},
                    {"course_code": "ai&ds6",
                     "class_id": 242,
                     "uid": 111},
                ]
                data.extend([
                    {"course_code": f"ece{year+3}",
                     "class_id": class_id,
                     "uid": 112}
                    for year in range(4, 8)
                    for class_id in range(311, 342,10)
                ])
                data.extend([
                    {"course_code": f"ece{year+3}",
                     "class_id": class_id,
                     "uid": 113}
                    for year in range(4, 8)
                    for class_id in range(312, 343,10)
                ])
                for i in data:
                    response = requests.post(url, json=i)
                    print(f"POST to {url} | Status Code: {response.status_code}")
                data = [
                    {"course_code": "cs1",
                    "uid": 103},
                   {"course_code": "cs2",
                    "uid": 107},
                   {"course_code": "cs3",
                    "uid": 108},
                   {"course_code": "cs4",
                    "uid": 109},
                ]  
                for i in data:
                    response = requests.post(f"{base_url}/assign_mentor", json=i)
                    print(f"POST to {url} | Status Code: {response.status_code}")

                data = [{
                    "domain_id":1,
                    "mentor_id": 104}]
                for i in data:
                    response = requests.post(f"{base_url}/assign_domain_mentor", json=i)
                    print(f"POST to {url} | Status Code: {response.status_code}")
            if i==3:
                data = [{
                    "course_code": "cs1",
                    "topic": "python 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },{"course_code": "cs1",
                    "topic": "python 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },
                {"course_code": "cs2",
                    "topic": "c 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },{"course_code": "cs2",
                    "topic": "c 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },
                {"course_code": "cs3",
                    "topic": "java 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },{"course_code": "cs3",
                    "topic": "java 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },
                {"course_code": "cs4",
                    "topic": "c++ 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },{"course_code": "cs4",
                    "topic": "c++ 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 101,
                },
                {"course_code": "ai&ds3",
                    "topic": "ai&ds topic 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 110,
                },{"course_code": "ai&ds3",
                    "topic": "ai&ds topic 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 111,
                },
                {"course_code": "ai&ds4",
                    "topic": "ai&ds topic 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 110,
                },{"course_code": "ai&ds4",
                    "topic": "ai&ds topic 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 111,
                },
                {"course_code": "ai&ds5",
                    "topic": "ai&ds topic 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 110,
                },{"course_code": "ai&ds5",
                    "topic": "ai&ds topic 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 111,
                },
                {"course_code": "ai&ds6",
                    "topic": "ai&ds topic 1",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 110,
                },{"course_code": "ai&ds6",
                    "topic": "ai&ds topic 2",
                    "outcome": "co1",
                    "total_hours": 5,
                    "uid": 111,
                }
                ]
                for i in data:
                    response = requests.post(url, json=i)
                    print(f"POST to {url} | Status Code: {response.status_code}")
        except requests.exceptions.RequestException as e:
            print(f"Failed to send POST to {url}: {e}\n")

if __name__ == "__main__":
    # Base URL of the API server
    base_url = "http://127.0.0.1:8000/api"

    # List of routes to send POST requests to
    routes = [
        "register",
        "add_course",
        "assign_course",
        "add_topic",
    ]

    # Data to send in the POST request
    userdata = [
        {"role": 1,
        "name": "Adithya",
        "password": "1",
        "department_id": 1,
        "id": 101},
        {"role": 1,
        "name": "Mitun",
        "password": "1",
        "department_id": 1,
        "id": 102},
        {"role": 1,
        "name": "John",
        "password": "1",
        "department_id": 2,
        "id": 110},
        {"role": 1,
        "name": "Jack",
        "password": "1",
        "department_id": 2,
        "id": 111},
        {"role": 1,
        "name": "Alice",
        "password": "1",
        "department_id": 3,
        "id": 112},
        {"role": 1,
        "name": "Bob",
        "password": "1",
        "department_id": 3,
        "id": 113},
        {"role": 1,
        "name": "Charlie",
        "password": "1",
        "department_id": 4,
        "id": 114},
        {"role": 1,
        "name": "David",
        "password": "1",
        "department_id": 4,
        "id": 115},
        {"role": 1,
        "name": "Eve",
        "password": "1",
        "department_id": 5,
        "id": 116},
        {"role": 1,
        "name": "Frank",
        "password": "1",
        "department_id": 5,
        "id": 117},
        {"role": 1,
        "name": "Grace",
        "password": "1",
        "department_id": 6,
        "id": 118},
        {"role": 1,
        "name": "Heidi",
        "password": "1",
        "department_id": 6,
        "id": 119},
        {"role": 1,
        "name": "Ivan",
        "password": "1",
        "department_id": 7,
        "id": 120},
        {"role": 1,
        "name": "Judy",
        "password": "1",
        "department_id": 7,
        "id": 121},
        {"role": 1,
        "name": "Mallory",
        "password": "1",
        "department_id": 8,
        "id": 122},
        {"role": 1,
        "name": "Oscar",
        "password": "1",
        "department_id": 8,
        "id": 123},
        {"role": 1,
        "name": "Peggy",
        "password": "1",
        "department_id": 9,
        "id": 124},
        {"role": 1,
        "name": "Trent",
        "password": "1",
        "department_id": 9,
        "id": 125},
        {"role": 2,
        "name": "RajaRajan",
        "password": "1",
        "department_id": 1,
        "id": 103},
        {"role": 2,
        "name": "Manoj",
        "password": "1",
        "department_id": 1,
        "id": 107},
        {"role": 2,
        "name": "Subash",
        "password": "1",
        "department_id": 1,
        "id": 108},
        {"role": 2,
        "name": "Monish",
        "password": "1",
        "department_id": 1,
        "id": 109},
        {"role": 3,
        "name": "Kabilan",
        "password": "1",
        "department_id": 1,
        "id": 104},
        {"role": 4,
        "name": "Nishanth",
        "password": "1",
        "department_id": 1,
        "id": 105},
        {"role": 5,
        "name": "Marudhu",
        "password": "1",
        "department_id": 1,
        "id": 106},
        ]

    # Send POST requests
    send_post_requests(base_url, routes, userdata)
